remote_theme: just-the-docs/just-the-docs
title: Rover Milestone
description: Documenting the engineering journey of building an autonomous rover.
plugins:
  - jekyll-remote-theme

# Navigation structure
nav:
  - Home: index.md
  - Physics:
      - Overview: physics/overview.md
      - Modules:
          - Module 1: physics/module_one/task_description.md