remote_theme: just-the-docs/just-the-docs
title: Rover Milestone
description: Documenting the engineering journey of building an autonomous rover.
plugins:
  - jekyll-remote-theme


exclude:
  - Dockerfile
  - docker-compose.yml