remote_theme: just-the-docs/just-the-docs
title: Rover Milestone
description: Documenting the engineering journey of building an autonomous rover.
plugins:
  - jekyll-remote-theme

head_scripts:
  - src: https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js

head_styles:
  - href: https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css

exclude:
  - Dockerfile
  - docker-compose.yml